### ISSUE TITLE
영어로 번역하기

### ISSUE THREAD

**Issue by hsh2001** [tmdgus0084/apple-dark-mode#3]
영어 잘하시는 분 계시면 나타나주세요 ㅠㅜ

**Comment by hsh2001** [comment]
[README.en.md](https://github.com/tmdgus0084/apple-dark-mode/blob/master/README.en.md)에서 도움 부탁드립니다...

**Comment by Bgh0602** [comment]
제가 도와드려도 될까요??

**Comment by hsh2001** [comment]
네 부탁드려요~
